### ISSUE TITLE
Gophish not able to launch

### ISSUE THREAD

**Issue by VikasSorabad** [STPIS/gophish#1]
Hi Team,

we are configuring gophish on windows environment. We just downloaded gophish and tried to run the gophish setup but the cmd prompt is throwing some error like, An attempt was made to access a socket in a way forbidden by its access permissions. 
we tried to change the port details in config file to 8080, 8888 & 81 but no help. 

Kindly help to resolve this issue.

**Comment by kp2021** [comment]
close it
